from django.urls import path
from foundation import web

urlpatterns = [
    path("truy-cap/uy-quyen/", web.delegation_request, name="delegation_request"),
    path("danh-muc/<slug:slug>/nhap-excel/", web.catalog_import, name="import"),
    path("trang-thai/", web.status, name="status"),
    path("tai-khoan/them/", web.account_new, name="account_new"),
    path("truy-cap/de-nghi/", web.access_request, name="access_request"),
    path("chung-tu/<uuid:key>/ban-giao/", web.handoff_new, name="handoff_new"),
    path("ban-giao/<uuid:key>/nhan/", web.handoff_reply, name="handoff_reply"),
    path("", web.home, name="home"),
    path("dang-nhap/", web.login, name="login"),
    path("dang-xuat/", web.logout, name="logout"),
    path("doi-mat-khau/", web.password, name="password"),
    path("doi-bo/", web.switch, name="switch"),
    path("danh-muc/<slug:slug>/", web.catalog_list, name="catalog"),
    path("danh-muc/<slug:slug>/them/", web.catalog_edit, name="catalog_new"),
    path("danh-muc/<slug:slug>/<uuid:key>/", web.catalog_edit, name="catalog_edit"),
    path("danh-muc/<slug:slug>/xuat/", web.catalog_export, name="export"),
    path("nhap/", web.draft, name="draft"),
    path("nhap/<uuid:key>/", web.draft_load, name="draft_load"),
    path("chung-tu/", web.documents, name="documents"),
    path("chung-tu/them/", web.new_document, name="document_new"),
    path("chung-tu/<uuid:key>/", web.document, name="document"),
    path("chung-tu/<uuid:key>/xu-ly/", web.document_action, name="document_action"),
    path("chung-tu/<uuid:key>/tep/", web.upload, name="upload"),
    path("tep/<uuid:key>/", web.file_download, name="file"),
    path("mo-dau/", web.openings, name="openings"),
    path("mo-dau/them/<slug:kind>/", web.opening_new, name="opening_new"),
    path("mo-dau/<uuid:key>/xac-nhan/<slug:kind>/", web.opening_post, name="opening_post"),
    path("mo-dau/<uuid:key>/qc/", web.opening_qc, name="opening_qc"),
    path("mo-dau/<uuid:key>/gia-tri/", web.opening_value, name="opening_value"),
    path("lich-su/", web.audit_list, name="audit"),
    path("truy-cap/", web.access, name="access"),
    path("truy-cap/<uuid:key>/ap-dung/", web.apply_access, name="apply_access"),
    path("suc-khoe/", web.health, name="health"),
]
