"""Labels shown to operators; storage enums remain stable Vietnamese identifiers."""

LABELS = dict(
    zip(
        "bao_ho bao_tri ben_ngoai ben_nhan_hang ben_tra_tien ben_van_chuyen bien_the canh_bao_ton cho_duong_ho chu_cong_trinh chuan_bi_may chuan_bi_vao_lam da_nghi_viec dai_ly dang_giao dang_su_dung dao_tao dinh_gia doi_don duong_ho duyet_mau gach_terrazzo hang_loat hoan_thien huan_luyen_an_toan khac_co_ly_do khach_hang khach_le kiem_chat_luong ky_nang lam_viec lich_lam may ngan_hang ngay_le nghi nghi_tuan ngoai_le ngoi nguon_luc nha_cung_cap nha_thau nhan nhan_vien nhom_mau phu_kien san_xuat su_co tam_ngung_lam tao_hinh thanh_pham the_tich thoi_gian thu_nhap thu_viec tien_mat tra_thay vat_tu vi_tri_thao_tac vien vung_trong_kho xac_dinh_gia xac_nhan_don xuat_khau xuong".split(),
        [
            "Bảo hộ",
            "Bảo trì",
            "Bên ngoài",
            "Bên nhận hàng",
            "Bên trả tiền",
            "Bên vận chuyển",
            "Biến thể",
            "Cảnh báo tồn",
            "Chờ dưỡng hộ",
            "Chủ công trình",
            "Chuẩn bị máy",
            "Chuẩn bị vào làm",
            "Đã nghỉ việc",
            "Đại lý",
            "Đang giao",
            "Đang sử dụng",
            "Đào tạo",
            "Định giá",
            "Đổi đơn",
            "Dưỡng hộ",
            "Duyệt mẫu",
            "Gạch Terrazzo",
            "Hàng loạt",
            "Hoàn thiện",
            "Huấn luyện an toàn",
            "Khác — có lý do",
            "Khách hàng",
            "Khách lẻ",
            "Kiểm chất lượng",
            "Kỹ năng",
            "Làm việc",
            "Lịch làm",
            "Máy",
            "Ngân hàng",
            "Ngày lễ",
            "Nghỉ",
            "Nghỉ tuần",
            "Ngoại lệ",
            "Ngói",
            "Nguồn lực",
            "Nhà cung cấp",
            "Nhà thầu",
            "Nhận",
            "Nhân viên",
            "Nhóm mẫu",
            "Phụ kiện",
            "Sản xuất",
            "Sự cố",
            "Tạm ngừng làm",
            "Tạo hình",
            "Thành phẩm",
            "Thể tích",
            "Thời gian",
            "Thu nhập",
            "Thử việc",
            "Tiền mặt",
            "Trả thay",
            "Vật tư",
            "Vị trí thao tác",
            "Viên",
            "Vùng trong kho",
            "Xác định giá",
            "Xác nhận đơn",
            "Xuất khẩu",
            "Xưởng",
        ],
    )
)
LABELS.update(
    {
        "nhap": "Nháp",
        "da_trinh": "Đã trình",
        "da_duyet": "Đã duyệt",
        "da_tu_choi": "Cần bổ sung",
        "khong_yeu_cau": "Không cần phê duyệt",
        "da_ghi_so": "Đã xác nhận",
        "cho_xu_ly": "Chờ xử lý",
        "dat": "Đạt",
        "loi": "Lỗi",
        "da_gui": "Đã gửi",
        "da_chap_nhan": "Đã nhận",
        "can_bo_sung": "Cần bổ sung",
        "quyet_dinh_danh_muc": "Quyết định danh mục",
        "quyet_dinh_chinh_sach": "Quyết định chính sách",
        "quyet_dinh_cap_quyen": "Quyết định quyền truy cập",
        "phan_cong": "Phân công",
        "ho_so_lam_viec": "Hồ sơ làm việc",
        "ton_dau": "Tồn đầu",
        "tien_dau": "Tiền đầu",
        "van_dong_hang": "Vận động hàng",
    }
)


def label(value):
    return LABELS.get(value, value) if isinstance(value, str) else value
